server:
  port: 9000
  shutdown: graceful

spring:
  application:
    name: authorization-server

logging:
  level:
    root: info
    io.starrychoon: debug
    org.springframework.web: debug
    org.springframework.security: trace
    org.springframework.security.oauth2: trace

provider:
  settings:
    issuer: http://auth-server:9000
    rsa:
      - public-key: classpath:jose/mykey.pub
        private-key: classpath:jose/mykey.pem
        key-id: mykey
